version: '3.7'

# Define services
services:
  # App backend service
  app-server:
    # Configuration for building the docker image for the backend service
    # build:
    #   context: springio/gep-docker # Use an image built from the specified dockerfile in the `polling-app-server` directory.
    #   dockerfile: Dockerfile
    image: "springio/gep-docker"
    container_name: "backend"
    ports:
      - "8080:8080" # Forward the exposed port 8080 on the container to port 8080 on the host machine
    restart: always
    networks: # Networks to join (Services on the same network can communicate with each other using their name)
      - backend
      - frontend

  # Frontend Service 
  app-client:
    # build:
    #   context: gep-react # Use an image built from the specified dockerfile in the `polling-app-client` directory.
    #   dockerfile: Dockerfile.prod
    image: "gep-react"
    container_name: "frontend"
    ports:
      - "9090:80" # Map the exposed port 80 on the container to port 9090 on the host machine
    restart: always
    depends_on:
      - app-server
    networks:
      - frontend  



# Networks to be created to facilitate communication between containers
networks:
  backend:
  frontend:    